# Generated by Django 4.1.3 on 2023-02-13 10:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mosaic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mosaic_type', models.CharField(max_length=100, null=True)),
                ('strength', models.CharField(max_length=100, null=True)),
                ('rect_number', models.TextField(max_length=100, null=True)),
                ('active_number', models.IntegerField(max_length=100, null=True)),
                ('image', models.ImageField(null=True, upload_to='images/')),
                ('rectangle', models.ImageField(null=True, upload_to='rectangles/')),
                ('result', models.ImageField(blank=True, null=True, upload_to='results/')),
            ],
        ),
    ]
