# Generated by Django 4.1.3 on 2022-12-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mosaics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mosaic",
            name="mosaic_type",
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name="mosaic",
            name="image",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
    ]
