# Generated by Django 4.1.3 on 2023-01-31 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mosaics", "0002_mosaic_mosaic_type_alter_mosaic_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="mosaic",
            name="strength",
            field=models.IntegerField(max_length=100, null=True),
        ),
    ]
