# Generated by Django 4.1.3 on 2023-02-01 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mosaics", "0003_mosaic_strength"),
    ]

    operations = [
        migrations.RemoveField(model_name="mosaic", name="title",),
    ]
